package com.ulab.client.webServiceRerigerator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-05-02T15:58:57.170+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://mgr", name = "servicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicePortType {

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getAllMetaData", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetAllMetaData")
    @WebMethod
    @ResponseWrapper(localName = "getAllMetaDataResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetAllMetaDataResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata getAllMetaData(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getCoordinationInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetCoordinationInfo")
    @WebMethod
    @ResponseWrapper(localName = "getCoordinationInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetCoordinationInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfCoordinateInfo getCoordinationInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getMetaDataNum", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetMetaDataNum")
    @WebMethod
    @ResponseWrapper(localName = "getMetaDataNumResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetMetaDataNumResponse")
    public int getMetaDataNum(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getMetaDataBegintoEnd", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetMetaDataBegintoEnd")
    @WebMethod
    @ResponseWrapper(localName = "getMetaDataBegintoEndResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetMetaDataBegintoEndResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata getMetaDataBegintoEnd(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://mgr")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://mgr")
        int in4
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSubWindowConfig", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSubWindowConfig")
    @WebMethod
    @ResponseWrapper(localName = "getSubWindowConfigResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSubWindowConfigResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSubWindowInfo getSubWindowConfig(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestMetaDataBySampleNo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestMetaDataBySampleNo")
    @WebMethod
    @ResponseWrapper(localName = "getTestMetaDataBySampleNoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestMetaDataBySampleNoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata getTestMetaDataBySampleNo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getGroupInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetGroupInfo")
    @WebMethod
    @ResponseWrapper(localName = "getGroupInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetGroupInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfGroupInfo getGroupInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSensorInformation", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorInformation")
    @WebMethod
    @ResponseWrapper(localName = "getSensorInformationResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorInformationResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSensorInfo getSensorInformation(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getReportClass", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetReportClass")
    @WebMethod
    @ResponseWrapper(localName = "getReportClassResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetReportClassResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfReportClass getReportClass(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getPLCInformation", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetPLCInformation")
    @WebMethod
    @ResponseWrapper(localName = "getPLCInformationResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetPLCInformationResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfPLCInformation getPLCInformation(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getOneMetaData", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetOneMetaData")
    @WebMethod
    @ResponseWrapper(localName = "getOneMetaDataResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetOneMetaDataResponse")
    public com.ulab.client.webServiceRerigerator.TestMetadata getOneMetaData(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getPLCInfoByPrimaryKey", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetPLCInfoByPrimaryKey")
    @WebMethod
    @ResponseWrapper(localName = "getPLCInfoByPrimaryKeyResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetPLCInfoByPrimaryKeyResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfPLCInformation getPLCInfoByPrimaryKey(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getAllMetaDataNum", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetAllMetaDataNum")
    @WebMethod
    @ResponseWrapper(localName = "getAllMetaDataNumResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetAllMetaDataNumResponse")
    public int getAllMetaDataNum(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSystemLanguage", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSystemLanguage")
    @WebMethod
    @ResponseWrapper(localName = "getSystemLanguageResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSystemLanguageResponse")
    public int getSystemLanguage();

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestUnitSensorTypeInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestUnitSensorTypeInfo")
    @WebMethod
    @ResponseWrapper(localName = "getTestUnitSensorTypeInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestUnitSensorTypeInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSensorTypeInfo getTestUnitSensorTypeInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getReportInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetReportInfo")
    @WebMethod
    @ResponseWrapper(localName = "getReportInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetReportInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfReportInfo getReportInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSensorTestDataByTime", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorTestDataByTime")
    @WebMethod
    @ResponseWrapper(localName = "getSensorTestDataByTimeResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorTestDataByTimeResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfString getSensorTestDataByTime(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        float in2,
        @WebParam(name = "in3", targetNamespace = "http://mgr")
        float in3
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getDeviceAlarmByPrimaryKey", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetDeviceAlarmByPrimaryKey")
    @WebMethod
    @ResponseWrapper(localName = "getDeviceAlarmByPrimaryKeyResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetDeviceAlarmByPrimaryKeyResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfDeviceAlarm getDeviceAlarmByPrimaryKey(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestResult", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestResult")
    @WebMethod
    @ResponseWrapper(localName = "getTestResultResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestResultResponse")
    public byte[] getTestResult(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestItem", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestItem")
    @WebMethod
    @ResponseWrapper(localName = "getTestItemResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestItemResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestItem getTestItem();

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getRealSensorTestData", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetRealSensorTestData")
    @WebMethod
    @ResponseWrapper(localName = "getRealSensorTestDataResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetRealSensorTestDataResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfString getRealSensorTestData(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        float in2
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getLatestSensorTestData", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetLatestSensorTestData")
    @WebMethod
    @ResponseWrapper(localName = "getLatestSensorTestDataResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetLatestSensorTestDataResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfString getLatestSensorTestData(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getItemEnergyByTime", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetItemEnergyByTime")
    @WebMethod
    @ResponseWrapper(localName = "getItemEnergyByTimeResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetItemEnergyByTimeResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfString getItemEnergyByTime(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getCoordinationConfigInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetCoordinationConfigInfo")
    @WebMethod
    @ResponseWrapper(localName = "getCoordinationConfigInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetCoordinationConfigInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfCoordinateInfo getCoordinationConfigInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestProdInfoItemByLabCode", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestProdInfoItemByLabCode")
    @WebMethod
    @ResponseWrapper(localName = "getTestProdInfoItemByLabCodeResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestProdInfoItemByLabCodeResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestProdInfoItem getTestProdInfoItemByLabCode(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSensorName", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorName")
    @WebMethod
    @ResponseWrapper(localName = "getSensorNameResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorNameResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSensorName getSensorName(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getWindowInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetWindowInfo")
    @WebMethod
    @ResponseWrapper(localName = "getWindowInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetWindowInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfWindowInfo getWindowInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getAllMetaDataBeginToEnd", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetAllMetaDataBeginToEnd")
    @WebMethod
    @ResponseWrapper(localName = "getAllMetaDataBeginToEndResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetAllMetaDataBeginToEndResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata getAllMetaDataBeginToEnd(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://mgr")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://mgr")
        int in4
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestReport", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestReport")
    @WebMethod
    @ResponseWrapper(localName = "getTestReportResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestReportResponse")
    public com.ulab.client.webServiceRerigerator.TestReport getTestReport(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSensorConfig", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorConfig")
    @WebMethod
    @ResponseWrapper(localName = "getSensorConfigResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorConfigResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSensorInfo getSensorConfig(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getGroupConfig", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetGroupConfig")
    @WebMethod
    @ResponseWrapper(localName = "getGroupConfigResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetGroupConfigResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfGroupConfig getGroupConfig(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getNozzleList", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetNozzleList")
    @WebMethod
    @ResponseWrapper(localName = "getNozzleListResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetNozzleListResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfNozzleList getNozzleList(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestResultMetaData", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestResultMetaData")
    @WebMethod
    @ResponseWrapper(localName = "getTestResultMetaDataResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestResultMetaDataResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestResultMetaData getTestResultMetaData(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestWorkingCondition", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestWorkingCondition")
    @WebMethod
    @ResponseWrapper(localName = "getTestWorkingConditionResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestWorkingConditionResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestWorkingCondition getTestWorkingCondition(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getNavigationInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetNavigationInfo")
    @WebMethod
    @ResponseWrapper(localName = "getNavigationInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetNavigationInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfNavigationInfo getNavigationInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getHello", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetHello")
    @WebMethod
    @ResponseWrapper(localName = "getHelloResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetHelloResponse")
    public java.lang.String getHello();

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSensorInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorInfo")
    @WebMethod
    @ResponseWrapper(localName = "getSensorInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSensorInfo getSensorInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getReportContent", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetReportContent")
    @WebMethod
    @ResponseWrapper(localName = "getReportContentResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetReportContentResponse")
    public byte[] getReportContent(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSubWindowInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSubWindowInfo")
    @WebMethod
    @ResponseWrapper(localName = "getSubWindowInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSubWindowInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSubWindowInfo getSubWindowInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestUnitInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestUnitInfo")
    @WebMethod
    @ResponseWrapper(localName = "getTestUnitInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestUnitInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestUnitInfo getTestUnitInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getCoordinateConfig", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetCoordinateConfig")
    @WebMethod
    @ResponseWrapper(localName = "getCoordinateConfigResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetCoordinateConfigResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfCoordinateInfo getCoordinateConfig(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getTestProdInfoItem", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestProdInfoItem")
    @WebMethod
    @ResponseWrapper(localName = "getTestProdInfoItemResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetTestProdInfoItemResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestProdInfoItem getTestProdInfoItem();

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getMetaData", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetMetaData")
    @WebMethod
    @ResponseWrapper(localName = "getMetaDataResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetMetaDataResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata getMetaData(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://mgr")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSystemInfo", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSystemInfo")
    @WebMethod
    @ResponseWrapper(localName = "getSystemInfoResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSystemInfoResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfSystemInfo getSystemInfo(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getDevelopType", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetDevelopType")
    @WebMethod
    @ResponseWrapper(localName = "getDevelopTypeResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetDevelopTypeResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfDevelopType getDevelopType();

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getSensorTestData", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorTestData")
    @WebMethod
    @ResponseWrapper(localName = "getSensorTestDataResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetSensorTestDataResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfString getSensorTestData(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getWindowConfig", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetWindowConfig")
    @WebMethod
    @ResponseWrapper(localName = "getWindowConfigResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetWindowConfigResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfWindowInfo getWindowConfig(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getDeviceAlarm", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetDeviceAlarm")
    @WebMethod
    @ResponseWrapper(localName = "getDeviceAlarmResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetDeviceAlarmResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfDeviceAlarm getDeviceAlarm(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://mgr")
    @RequestWrapper(localName = "getWorkingConditionTestByPrimaryKey", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetWorkingConditionTestByPrimaryKey")
    @WebMethod
    @ResponseWrapper(localName = "getWorkingConditionTestByPrimaryKeyResponse", targetNamespace = "http://mgr", className = "com.ulab.client.webServiceRerigerator.GetWorkingConditionTestByPrimaryKeyResponse")
    public com.ulab.client.webServiceRerigerator.ArrayOfTestWorkingCondition getWorkingConditionTestByPrimaryKey(
        @WebParam(name = "in0", targetNamespace = "http://mgr")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://mgr")
        java.lang.String in1
    );
}
