
package com.ulab.client.webServiceRerigerator;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-05-02T15:58:57.121+08:00
 * Generated source version: 2.4.3
 * 
 */
public final class ServicePortType_ServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://mgr", "service");

    private ServicePortType_ServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service ss = new Service(wsdlURL, SERVICE_NAME);
        ServicePortType port = ss.getServiceHttpPort();  
        
        {
        System.out.println("Invoking getAllMetaData...");
        java.lang.String _getAllMetaData_in0 = "";
        int _getAllMetaData_in1 = 0;
        int _getAllMetaData_in2 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata _getAllMetaData__return = port.getAllMetaData(_getAllMetaData_in0, _getAllMetaData_in1, _getAllMetaData_in2);
        System.out.println("getAllMetaData.result=" + _getAllMetaData__return);


        }
        {
        System.out.println("Invoking getCoordinationInfo...");
        java.lang.String _getCoordinationInfo_in0 = "";
        java.lang.String _getCoordinationInfo_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfCoordinateInfo _getCoordinationInfo__return = port.getCoordinationInfo(_getCoordinationInfo_in0, _getCoordinationInfo_in1);
        System.out.println("getCoordinationInfo.result=" + _getCoordinationInfo__return);


        }
        {
        System.out.println("Invoking getMetaDataNum...");
        java.lang.String _getMetaDataNum_in0 = "";
        int _getMetaDataNum_in1 = 0;
        java.lang.String _getMetaDataNum_in2 = "";
        int _getMetaDataNum__return = port.getMetaDataNum(_getMetaDataNum_in0, _getMetaDataNum_in1, _getMetaDataNum_in2);
        System.out.println("getMetaDataNum.result=" + _getMetaDataNum__return);


        }
        {
        System.out.println("Invoking getMetaDataBegintoEnd...");
        java.lang.String _getMetaDataBegintoEnd_in0 = "";
        int _getMetaDataBegintoEnd_in1 = 0;
        java.lang.String _getMetaDataBegintoEnd_in2 = "";
        int _getMetaDataBegintoEnd_in3 = 0;
        int _getMetaDataBegintoEnd_in4 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata _getMetaDataBegintoEnd__return = port.getMetaDataBegintoEnd(_getMetaDataBegintoEnd_in0, _getMetaDataBegintoEnd_in1, _getMetaDataBegintoEnd_in2, _getMetaDataBegintoEnd_in3, _getMetaDataBegintoEnd_in4);
        System.out.println("getMetaDataBegintoEnd.result=" + _getMetaDataBegintoEnd__return);


        }
        {
        System.out.println("Invoking getSubWindowConfig...");
        java.lang.String _getSubWindowConfig_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfSubWindowInfo _getSubWindowConfig__return = port.getSubWindowConfig(_getSubWindowConfig_in0);
        System.out.println("getSubWindowConfig.result=" + _getSubWindowConfig__return);


        }
        {
        System.out.println("Invoking getTestMetaDataBySampleNo...");
        java.lang.String _getTestMetaDataBySampleNo_in0 = "";
        java.lang.String _getTestMetaDataBySampleNo_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata _getTestMetaDataBySampleNo__return = port.getTestMetaDataBySampleNo(_getTestMetaDataBySampleNo_in0, _getTestMetaDataBySampleNo_in1);
        System.out.println("getTestMetaDataBySampleNo.result=" + _getTestMetaDataBySampleNo__return);


        }
        {
        System.out.println("Invoking getGroupInfo...");
        java.lang.String _getGroupInfo_in0 = "";
        java.lang.String _getGroupInfo_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfGroupInfo _getGroupInfo__return = port.getGroupInfo(_getGroupInfo_in0, _getGroupInfo_in1);
        System.out.println("getGroupInfo.result=" + _getGroupInfo__return);


        }
        {
        System.out.println("Invoking getSensorInformation...");
        java.lang.String _getSensorInformation_in0 = "";
        java.lang.String _getSensorInformation_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfSensorInfo _getSensorInformation__return = port.getSensorInformation(_getSensorInformation_in0, _getSensorInformation_in1);
        System.out.println("getSensorInformation.result=" + _getSensorInformation__return);


        }
        {
        System.out.println("Invoking getReportClass...");
        java.lang.String _getReportClass_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfReportClass _getReportClass__return = port.getReportClass(_getReportClass_in0);
        System.out.println("getReportClass.result=" + _getReportClass__return);


        }
        {
        System.out.println("Invoking getPLCInformation...");
        java.lang.String _getPLCInformation_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfPLCInformation _getPLCInformation__return = port.getPLCInformation(_getPLCInformation_in0);
        System.out.println("getPLCInformation.result=" + _getPLCInformation__return);


        }
        {
        System.out.println("Invoking getOneMetaData...");
        java.lang.String _getOneMetaData_in0 = "";
        java.lang.String _getOneMetaData_in1 = "";
        com.ulab.client.webServiceRerigerator.TestMetadata _getOneMetaData__return = port.getOneMetaData(_getOneMetaData_in0, _getOneMetaData_in1);
        System.out.println("getOneMetaData.result=" + _getOneMetaData__return);


        }
        {
        System.out.println("Invoking getPLCInfoByPrimaryKey...");
        java.lang.String _getPLCInfoByPrimaryKey_in0 = "";
        java.lang.String _getPLCInfoByPrimaryKey_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfPLCInformation _getPLCInfoByPrimaryKey__return = port.getPLCInfoByPrimaryKey(_getPLCInfoByPrimaryKey_in0, _getPLCInfoByPrimaryKey_in1);
        System.out.println("getPLCInfoByPrimaryKey.result=" + _getPLCInfoByPrimaryKey__return);


        }
        {
        System.out.println("Invoking getAllMetaDataNum...");
        java.lang.String _getAllMetaDataNum_in0 = "";
        int _getAllMetaDataNum_in1 = 0;
        int _getAllMetaDataNum_in2 = 0;
        int _getAllMetaDataNum__return = port.getAllMetaDataNum(_getAllMetaDataNum_in0, _getAllMetaDataNum_in1, _getAllMetaDataNum_in2);
        System.out.println("getAllMetaDataNum.result=" + _getAllMetaDataNum__return);


        }
        {
        System.out.println("Invoking getSystemLanguage...");
        int _getSystemLanguage__return = port.getSystemLanguage();
        System.out.println("getSystemLanguage.result=" + _getSystemLanguage__return);


        }
        {
        System.out.println("Invoking getTestUnitSensorTypeInfo...");
        java.lang.String _getTestUnitSensorTypeInfo_in0 = "";
        int _getTestUnitSensorTypeInfo_in1 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfSensorTypeInfo _getTestUnitSensorTypeInfo__return = port.getTestUnitSensorTypeInfo(_getTestUnitSensorTypeInfo_in0, _getTestUnitSensorTypeInfo_in1);
        System.out.println("getTestUnitSensorTypeInfo.result=" + _getTestUnitSensorTypeInfo__return);


        }
        {
        System.out.println("Invoking getReportInfo...");
        java.lang.String _getReportInfo_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfReportInfo _getReportInfo__return = port.getReportInfo(_getReportInfo_in0);
        System.out.println("getReportInfo.result=" + _getReportInfo__return);


        }
        {
        System.out.println("Invoking getSensorTestDataByTime...");
        java.lang.String _getSensorTestDataByTime_in0 = "";
        java.lang.String _getSensorTestDataByTime_in1 = "";
        float _getSensorTestDataByTime_in2 = 0.0f;
        float _getSensorTestDataByTime_in3 = 0.0f;
        com.ulab.client.webServiceRerigerator.ArrayOfString _getSensorTestDataByTime__return = port.getSensorTestDataByTime(_getSensorTestDataByTime_in0, _getSensorTestDataByTime_in1, _getSensorTestDataByTime_in2, _getSensorTestDataByTime_in3);
        System.out.println("getSensorTestDataByTime.result=" + _getSensorTestDataByTime__return);


        }
        {
        System.out.println("Invoking getDeviceAlarmByPrimaryKey...");
        java.lang.String _getDeviceAlarmByPrimaryKey_in0 = "";
        java.lang.String _getDeviceAlarmByPrimaryKey_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfDeviceAlarm _getDeviceAlarmByPrimaryKey__return = port.getDeviceAlarmByPrimaryKey(_getDeviceAlarmByPrimaryKey_in0, _getDeviceAlarmByPrimaryKey_in1);
        System.out.println("getDeviceAlarmByPrimaryKey.result=" + _getDeviceAlarmByPrimaryKey__return);


        }
        {
        System.out.println("Invoking getTestResult...");
        java.lang.String _getTestResult_in0 = "";
        java.lang.String _getTestResult_in1 = "";
        int _getTestResult_in2 = 0;
        byte[] _getTestResult__return = port.getTestResult(_getTestResult_in0, _getTestResult_in1, _getTestResult_in2);
        System.out.println("getTestResult.result=" + _getTestResult__return);


        }
        {
        System.out.println("Invoking getTestItem...");
        com.ulab.client.webServiceRerigerator.ArrayOfTestItem _getTestItem__return = port.getTestItem();
        System.out.println("getTestItem.result=" + _getTestItem__return);


        }
        {
        System.out.println("Invoking getRealSensorTestData...");
        java.lang.String _getRealSensorTestData_in0 = "";
        java.lang.String _getRealSensorTestData_in1 = "";
        float _getRealSensorTestData_in2 = 0.0f;
        com.ulab.client.webServiceRerigerator.ArrayOfString _getRealSensorTestData__return = port.getRealSensorTestData(_getRealSensorTestData_in0, _getRealSensorTestData_in1, _getRealSensorTestData_in2);
        System.out.println("getRealSensorTestData.result=" + _getRealSensorTestData__return);


        }
        {
        System.out.println("Invoking getLatestSensorTestData...");
        java.lang.String _getLatestSensorTestData_in0 = "";
        java.lang.String _getLatestSensorTestData_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfString _getLatestSensorTestData__return = port.getLatestSensorTestData(_getLatestSensorTestData_in0, _getLatestSensorTestData_in1);
        System.out.println("getLatestSensorTestData.result=" + _getLatestSensorTestData__return);


        }
        {
        System.out.println("Invoking getItemEnergyByTime...");
        java.lang.String _getItemEnergyByTime_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfString _getItemEnergyByTime__return = port.getItemEnergyByTime(_getItemEnergyByTime_in0);
        System.out.println("getItemEnergyByTime.result=" + _getItemEnergyByTime__return);


        }
        {
        System.out.println("Invoking getCoordinationConfigInfo...");
        java.lang.String _getCoordinationConfigInfo_in0 = "";
        int _getCoordinationConfigInfo_in1 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfCoordinateInfo _getCoordinationConfigInfo__return = port.getCoordinationConfigInfo(_getCoordinationConfigInfo_in0, _getCoordinationConfigInfo_in1);
        System.out.println("getCoordinationConfigInfo.result=" + _getCoordinationConfigInfo__return);


        }
        {
        System.out.println("Invoking getTestProdInfoItemByLabCode...");
        java.lang.String _getTestProdInfoItemByLabCode_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfTestProdInfoItem _getTestProdInfoItemByLabCode__return = port.getTestProdInfoItemByLabCode(_getTestProdInfoItemByLabCode_in0);
        System.out.println("getTestProdInfoItemByLabCode.result=" + _getTestProdInfoItemByLabCode__return);


        }
        {
        System.out.println("Invoking getSensorName...");
        java.lang.String _getSensorName_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfSensorName _getSensorName__return = port.getSensorName(_getSensorName_in0);
        System.out.println("getSensorName.result=" + _getSensorName__return);


        }
        {
        System.out.println("Invoking getWindowInfo...");
        java.lang.String _getWindowInfo_in0 = "";
        int _getWindowInfo_in1 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfWindowInfo _getWindowInfo__return = port.getWindowInfo(_getWindowInfo_in0, _getWindowInfo_in1);
        System.out.println("getWindowInfo.result=" + _getWindowInfo__return);


        }
        {
        System.out.println("Invoking getAllMetaDataBeginToEnd...");
        java.lang.String _getAllMetaDataBeginToEnd_in0 = "";
        int _getAllMetaDataBeginToEnd_in1 = 0;
        int _getAllMetaDataBeginToEnd_in2 = 0;
        int _getAllMetaDataBeginToEnd_in3 = 0;
        int _getAllMetaDataBeginToEnd_in4 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata _getAllMetaDataBeginToEnd__return = port.getAllMetaDataBeginToEnd(_getAllMetaDataBeginToEnd_in0, _getAllMetaDataBeginToEnd_in1, _getAllMetaDataBeginToEnd_in2, _getAllMetaDataBeginToEnd_in3, _getAllMetaDataBeginToEnd_in4);
        System.out.println("getAllMetaDataBeginToEnd.result=" + _getAllMetaDataBeginToEnd__return);


        }
        {
        System.out.println("Invoking getTestReport...");
        java.lang.String _getTestReport_in0 = "";
        java.lang.String _getTestReport_in1 = "";
        com.ulab.client.webServiceRerigerator.TestReport _getTestReport__return = port.getTestReport(_getTestReport_in0, _getTestReport_in1);
        System.out.println("getTestReport.result=" + _getTestReport__return);


        }
        {
        System.out.println("Invoking getSensorConfig...");
        java.lang.String _getSensorConfig_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfSensorInfo _getSensorConfig__return = port.getSensorConfig(_getSensorConfig_in0);
        System.out.println("getSensorConfig.result=" + _getSensorConfig__return);


        }
        {
        System.out.println("Invoking getGroupConfig...");
        java.lang.String _getGroupConfig_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfGroupConfig _getGroupConfig__return = port.getGroupConfig(_getGroupConfig_in0);
        System.out.println("getGroupConfig.result=" + _getGroupConfig__return);


        }
        {
        System.out.println("Invoking getNozzleList...");
        java.lang.String _getNozzleList_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfNozzleList _getNozzleList__return = port.getNozzleList(_getNozzleList_in0);
        System.out.println("getNozzleList.result=" + _getNozzleList__return);


        }
        {
        System.out.println("Invoking getTestResultMetaData...");
        java.lang.String _getTestResultMetaData_in0 = "";
        java.lang.String _getTestResultMetaData_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfTestResultMetaData _getTestResultMetaData__return = port.getTestResultMetaData(_getTestResultMetaData_in0, _getTestResultMetaData_in1);
        System.out.println("getTestResultMetaData.result=" + _getTestResultMetaData__return);


        }
        {
        System.out.println("Invoking getTestWorkingCondition...");
        java.lang.String _getTestWorkingCondition_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfTestWorkingCondition _getTestWorkingCondition__return = port.getTestWorkingCondition(_getTestWorkingCondition_in0);
        System.out.println("getTestWorkingCondition.result=" + _getTestWorkingCondition__return);


        }
        {
        System.out.println("Invoking getNavigationInfo...");
        java.lang.String _getNavigationInfo_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfNavigationInfo _getNavigationInfo__return = port.getNavigationInfo(_getNavigationInfo_in0);
        System.out.println("getNavigationInfo.result=" + _getNavigationInfo__return);


        }
        {
        System.out.println("Invoking getHello...");
        java.lang.String _getHello__return = port.getHello();
        System.out.println("getHello.result=" + _getHello__return);


        }
        {
        System.out.println("Invoking getSensorInfo...");
        java.lang.String _getSensorInfo_in0 = "";
        int _getSensorInfo_in1 = 0;
        int _getSensorInfo_in2 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfSensorInfo _getSensorInfo__return = port.getSensorInfo(_getSensorInfo_in0, _getSensorInfo_in1, _getSensorInfo_in2);
        System.out.println("getSensorInfo.result=" + _getSensorInfo__return);


        }
        {
        System.out.println("Invoking getReportContent...");
        java.lang.String _getReportContent_in0 = "";
        int _getReportContent_in1 = 0;
        byte[] _getReportContent__return = port.getReportContent(_getReportContent_in0, _getReportContent_in1);
        System.out.println("getReportContent.result=" + _getReportContent__return);


        }
        {
        System.out.println("Invoking getSubWindowInfo...");
        java.lang.String _getSubWindowInfo_in0 = "";
        int _getSubWindowInfo_in1 = 0;
        com.ulab.client.webServiceRerigerator.ArrayOfSubWindowInfo _getSubWindowInfo__return = port.getSubWindowInfo(_getSubWindowInfo_in0, _getSubWindowInfo_in1);
        System.out.println("getSubWindowInfo.result=" + _getSubWindowInfo__return);


        }
        {
        System.out.println("Invoking getTestUnitInfo...");
        java.lang.String _getTestUnitInfo_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfTestUnitInfo _getTestUnitInfo__return = port.getTestUnitInfo(_getTestUnitInfo_in0);
        System.out.println("getTestUnitInfo.result=" + _getTestUnitInfo__return);


        }
        {
        System.out.println("Invoking getCoordinateConfig...");
        java.lang.String _getCoordinateConfig_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfCoordinateInfo _getCoordinateConfig__return = port.getCoordinateConfig(_getCoordinateConfig_in0);
        System.out.println("getCoordinateConfig.result=" + _getCoordinateConfig__return);


        }
        {
        System.out.println("Invoking getTestProdInfoItem...");
        com.ulab.client.webServiceRerigerator.ArrayOfTestProdInfoItem _getTestProdInfoItem__return = port.getTestProdInfoItem();
        System.out.println("getTestProdInfoItem.result=" + _getTestProdInfoItem__return);


        }
        {
        System.out.println("Invoking getMetaData...");
        java.lang.String _getMetaData_in0 = "";
        int _getMetaData_in1 = 0;
        java.lang.String _getMetaData_in2 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfTestMetadata _getMetaData__return = port.getMetaData(_getMetaData_in0, _getMetaData_in1, _getMetaData_in2);
        System.out.println("getMetaData.result=" + _getMetaData__return);


        }
        {
        System.out.println("Invoking getSystemInfo...");
        java.lang.String _getSystemInfo_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfSystemInfo _getSystemInfo__return = port.getSystemInfo(_getSystemInfo_in0);
        System.out.println("getSystemInfo.result=" + _getSystemInfo__return);


        }
        {
        System.out.println("Invoking getDevelopType...");
        com.ulab.client.webServiceRerigerator.ArrayOfDevelopType _getDevelopType__return = port.getDevelopType();
        System.out.println("getDevelopType.result=" + _getDevelopType__return);


        }
        {
        System.out.println("Invoking getSensorTestData...");
        java.lang.String _getSensorTestData_in0 = "";
        java.lang.String _getSensorTestData_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfString _getSensorTestData__return = port.getSensorTestData(_getSensorTestData_in0, _getSensorTestData_in1);
        System.out.println("getSensorTestData.result=" + _getSensorTestData__return);


        }
        {
        System.out.println("Invoking getWindowConfig...");
        java.lang.String _getWindowConfig_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfWindowInfo _getWindowConfig__return = port.getWindowConfig(_getWindowConfig_in0);
        System.out.println("getWindowConfig.result=" + _getWindowConfig__return);


        }
        {
        System.out.println("Invoking getDeviceAlarm...");
        java.lang.String _getDeviceAlarm_in0 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfDeviceAlarm _getDeviceAlarm__return = port.getDeviceAlarm(_getDeviceAlarm_in0);
        System.out.println("getDeviceAlarm.result=" + _getDeviceAlarm__return);


        }
        {
        System.out.println("Invoking getWorkingConditionTestByPrimaryKey...");
        java.lang.String _getWorkingConditionTestByPrimaryKey_in0 = "";
        java.lang.String _getWorkingConditionTestByPrimaryKey_in1 = "";
        com.ulab.client.webServiceRerigerator.ArrayOfTestWorkingCondition _getWorkingConditionTestByPrimaryKey__return = port.getWorkingConditionTestByPrimaryKey(_getWorkingConditionTestByPrimaryKey_in0, _getWorkingConditionTestByPrimaryKey_in1);
        System.out.println("getWorkingConditionTestByPrimaryKey.result=" + _getWorkingConditionTestByPrimaryKey__return);


        }

        System.exit(0);
    }

}
